version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config
  python: circleci/python@1.3.3 # Use the Python orb in this config

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: ./manage.py test --database=sqlite
          name: Test


workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch